### ISSUE TITLE
[Q] Why UUID, but not instance?

### ISSUE THREAD

**Issue by sanmai** [phpsci/phpsci-ext#23]
Why can't `CArray::destroy` and other functions can't take an instance?

This seems to be a certain usability problem. Not only one has to mention this in the docs here and there, but a user must take excessive care to handle UUIDs. Any why would someone to destroy an object with an UUID in the first place.

Please forgive me if that's on the roadmap.

**Comment by henrique-borba** [comment]
Hey @sanmai 

Yeah it sucks! In the beginning, due to lack of documentation and lack of knowledge about PHP internals, I decided not to instantiate and go straight to solve the initial problem, leaving that control of uuids and shapes with the composer library.

Before, none of the methods returned the rows and columns, now as the CArray object already comes with these pre-computed values, I will start changing the methods to receive the object and thus finish with this excess parameters. I will commit it today.

## Roadmap

Considering that now I am no longer a solitary developer in this project, I believe that I must open a issue to decide the roadmap for version 0.1 (not 1.0 anymore, 1.0 is too stable for the first release I think) as well as to define the standards of contribution . 

I will open this issue today to receive your feedback as soon as possible.

again, thank you!

**Comment by henrique-borba** [comment]
Closing this issue as Roadmap Discussion (#25) was created.
